name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install jackd libjack0 libjack-dev
      - name: Start dummy JACK server
        run: jackd -r -ddummy -r44100 -p1024 &
      - name: Lint
        run: |
          cargo clippy --all-targets -- -D clippy::all
          cargo clippy --all-targets --features dlopen -- -D clippy::all
          cargo clippy --all-targets --features metadata -- -D clippy::all
          cargo clippy --all-targets --features dlopen,metadata -- -D clippy::all
      - name: Build
        run: |
          cargo build --verbose
          cargo build --verbose --features dlopen
          cargo build --verbose --features metadata
          cargo build --verbose --features dlopen,metadata
      - name: Run Tests
        run: RUST_TEST_THREADS=1 cargo test --verbose
      - name: Run Tests with dlopen
        run: RUST_TEST_THREADS=1 cargo test --features dlopen --verbose
      - name: Run Tests with metadata
        run: RUST_TEST_THREADS=1 cargo test --features metadata --verbose
      - name: Run Tests with dlopen and metadata
        run: RUST_TEST_THREADS=1 cargo test --features dlopen,metadata --verbose
